version: "3.8"

services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres:
